# Generated by Django 2.0.1 on 2018-01-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=256)),
                ('date', models.DateTimeField(default=0, max_length=128)),
                ('title', models.CharField(default=0, max_length=150)),
                ('body', models.TextField(default=0, max_length=4096)),
                ('timestamp', models.DateTimeField(default=0, max_length=32)),
            ],
        ),
    ]
